__main__.Company:
  event_router: recall.event_router.AMQP

recall.event_router.AMQP:
  connection:
    host: 127.0.0.1
  exchange:
    exchange: reputation.demo
    type: topic
  queue:
    exchange: reputation.demo
    name: reputation.demo