__main__.Account:
  event_router: recall.event_router.AMQP
  snapshot_store: recall.snapshot_store.Memcached
  event_store: recall.event_store.Redis

recall.event_router.AMQP:
  connection:
    host: localhost
    port: 5672
    virtual_host: "/"
    username: guest
    password: guest
  exchange:
    exchange: mailing.tracker
    type: topic

recall.snapshot_store.Memcached:
  servers: [ "127.0.0.1:11211" ]

recall.event_store.Redis:
  host: localhost
  port: 6379
  db: 0