__main__.Account:
  event_router: recall.event_router.AMQP
  snapshot_store: recall.snapshot_store.Memcached

recall.event_router.AMQP:
  connection:
    host: localhost
    port: 5672
    virtual_host: "/"
    username: guest
    password: guest
  exchange:
    exchange: mailing.tracker
    type: topic

recall.snapshot_store.Memcached:
  servers: [ "127.0.0.1:11211" ]