__main__.Account:
  event_router: recall.event_router.AMQP

recall.event_router.AMQP:
  connection:
    host: localhost
    port: 5672
    virtual_host: "/"
    username: guest
    password: guest
  exchange:
    exchange: mailing.tracker
    type: topic